# Generated by Django 4.0.5 on 2022-07-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password2',
        ),
    ]
