# Generated by Django 4.0.6 on 2022-07-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project_progress',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
