# Generated by Django 4.0.6 on 2022-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0004_alter_student_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_no',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
