# Generated by Django 4.0.6 on 2022-07-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0006_student_project_link_alter_student_group_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='project_link',
            field=models.URLField(blank=True, default='', max_length=100, null=True),
        ),
    ]
