# Generated by Django 4.0.6 on 2022-07-24 08:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0008_teacher_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', multiselectfield.db.fields.MultiSelectField(choices=[('0', 'zeroth review'), ('1', 'first review'), ('2', 'second review'), ('3', 'third review'), ('4', 'fourth review')], max_length=9, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='time',
        ),
    ]
