# Generated by Django 4.0.6 on 2022-07-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0009_timeline_remove_teacher_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeLine',
            new_name='Time_line',
        ),
    ]
