# Generated by Django 4.0.6 on 2022-07-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0012_alter_time_line_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_line',
            name='time',
        ),
        migrations.AddField(
            model_name='time_line',
            name='first',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='time_line',
            name='fourth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='time_line',
            name='second',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='time_line',
            name='third',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='time_line',
            name='zero',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
